# Generated by Django 5.1.1 on 2025-02-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
